# TATR configuration for table structure recognition

model:
  name: tatr
  backbone: resnet34  # Lighter backbone for efficiency
  
  # Transformer settings
  d_model: 256
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  
  # Object queries
  num_queries: 125  # Max table elements
  
  # Structure classes
  num_classes: 6
  class_names:
    - table
    - table_column
    - table_row
    - table_column_header
    - table_projected_row_header
    - table_spanning_cell

data:
  # 明示指定（簡易）: 画像ディレクトリと注釈JSON（boxes[cx,cy,w,h], labels）
  images_dir: data/table/images
  annotations: data/table/annotations.json
  batch_size: 4
  num_workers: 4
  
  # Image preprocessing
  train_transform:
    - type: resize
      size: [800, 800]
      max_size: 1333
    - type: random_crop
      prob: 0.5
    - type: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
  val_transform:
    - type: resize
      size: [800, 800]
      max_size: 1333
    - type: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

training:
  epochs: 10
  optimizer:
    type: AdamW
    lr: 0.0001
    weight_decay: 0.0001
  
  scheduler:
    type: StepLR
    step_size: 100
    gamma: 0.1
  
  # Loss weights
  loss:
    # Hungarian matcher costs
    cost_class: 1.0
    cost_bbox: 5.0
    cost_giou: 2.0
    
    # Loss coefficients
    loss_ce: 1.0      # class loss
    loss_bbox: 5.0    # bbox L1 loss
    loss_giou: 2.0    # generalized IoU loss
    
    # Auxiliary loss
    aux_loss: true
    
  # Gradient clipping
  clip_max_norm: 0.1
  
  # Mixed precision
  use_amp: true
  
  # Checkpointing
  save_period: 20
  save_best: true
  
  # Early stopping
  patience: 30

evaluation:
  # Metrics
  metrics:
    - TEDS  # Tree Edit Distance Similarity
    - precision
    - recall
    - f1
  
  # Structure-specific metrics
  structure_metrics:
    - row_detection_accuracy
    - column_detection_accuracy
    - cell_detection_accuracy
    - header_detection_accuracy
  
  # TEDS calculation
  teds:
    structure_weight: 0.5
    content_weight: 0.5
    
  # Post-processing
  postprocess:
    confidence_threshold: 0.5
    max_detections: 200

inference:
  # Two-stage inference
  stages:
    - task: detection  # Detect table regions
      conf_threshold: 0.5
    - task: structure  # Recognize structure
      conf_threshold: 0.3
  
  # Cell merging
  merge_cells: true
  merge_threshold: 0.8
  
  # HTML/Markdown generation
  generate_html: true
  generate_markdown: true
